apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: langflow-https
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`langflow.delo.sh`)
      kind: Rule
      services:
        - name: langflow-external
          port: 7860
  tls:
    secretName: langflow-delo-sh-tls
---
apiVersion: v1
kind: Service
metadata:
  name: langflow-external
  namespace: default
spec:
  ports:
    - protocol: TCP
      port: 7860
      targetPort: 7860
---
apiVersion: v1
kind: Endpoints
metadata:
  name: langflow-external
  namespace: default
subsets:
  - addresses:
      - ip: 192.168.1.12
    ports:
      - port: 7860
