version: '3.5'

services:
  flexisip:
    build:
      context: ./src
      dockerfile: docker/Dockerfile.debian
    container_name: flexisip
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./config/flexisip.conf:/etc/flexisip/flexisip.conf
      - ./apn:/etc/flexisip/apn
      - ./firebase:/etc/flexisip/firebase
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - flexisip-redis
      - flexisip-mariadb

  flexisip-redis:
    image: redis:7-alpine
    container_name: flexisip-redis
    restart: unless-stopped
    command: redis-server --save 60 1 --loglevel warning
    ports:
      - "127.0.0.1:6380:6379"
    volumes:
      - flexisip_redis_data:/data
    networks:
      - default

  flexisip-mariadb:
    image: mariadb:10
    container_name: flexisip-mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: flexisip_root_password # Change this in production
      MYSQL_DATABASE: flexisip
      MYSQL_USER: flexisip
      MYSQL_PASSWORD: flexisip_password # Change this in production
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - flexisip_db_data:/var/lib/mysql
    networks:
      - default

volumes:
  flexisip_redis_data:
  flexisip_db_data:
