tls:
  certificates:
    - certFile: /certs/n8n.crt
      keyFile: /certs/n8n.key
      stores:
        - default
  stores:
    default:
      defaultCertificate:
        certFile: /certs/n8n.crt
        keyFile: /certs/n8n.key
