http:
  middlewares:
    nas-headers:
      headers:
        customRequestHeaders:
          X-Forwarded-Proto: "https"
          X-Forwarded-Prefix: "/"

  routers:
    nas:
      rule: "Host(`emma.delo.sh`)"
      entryPoints:
        - websecure
      service: nas
      middlewares:
        - nas-headers
      tls:
        certResolver: letsencrypt

  services:
    nas:
      loadBalancer:
        servers:
          - url: "http://192.168.1.50:5000"
