services:
  open-webui:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG-main}
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data
    ports:
      - ${OPEN_WEBUI_PORT-8670}:8080
    environment:
      - "OLLAMA_BASE_URL=http://192.168.1.12:11434"
      - "WEBUI_SECRET_KEY=peepeecharlie00XXxx"
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ai.rule=Host(`ai.delo.sh`)"
      - "traefik.http.routers.ai.entrypoints=websecure"
      - "traefik.http.routers.ai.tls.certresolver=letsencrypt"
      - "traefik.http.services.ai.loadbalancer.server.port=8080"
      - "traefik.docker.network=proxy"
    networks:
      - proxy

volumes:
  open-webui: {}

networks:
  proxy:
    external: true
